In [3]:
import pandas as pd
import numpy as np
%matplotlib inline

In [38]:
path1 = "Erstsprache/Erstsprache nach Schulstufe_2017.xls"
path2 = "Erstsprache/Erstsprache nach Schulstufe_2016.xls"

In [44]:
df1 = pd.read_excel(path1)
df2 = pd.read_excel(path2)

In [42]:
df1

,Erstsprache nach Schulstufe,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Stand: 02.10.2019 / Bildungsstatistik Kanton zh],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Jahr,Schulgemeinde,Erstsprache,KG,PS,PS Sonder,Sek A,Sek B,Sek C,Sek Sonder,Total
4,2017,Adlikon (Primar),Deutsch,0,12,0,NaN,NaN,NaN,NaN,12
...,...,...,...,...,...,...,...,...,...,...,...
4596,2017,Zürich-Zürichberg (Kreisschulpflege),Übrige osteuropäische Sprachen,0,3,0,0,0,0,0,3
4597,2017,Zürich-Zürichberg (Kreisschulpflege),Übrige slawische Sprachen,0,2,0,0,0,0,0,2
4598,2017,Zürich-Zürichberg (Kreisschulpflege),Übrige Sprachen,0,11,0,0,0,0,1,12
4599,2017,Zürich-Zürichberg (Kreisschulpflege),Übrige westasiatische Sprachen,0,1,0,0,0,0,0,1
4600,2017,Zürich-Zürichberg (Kreisschulpflege),Ungarisch,2,9,0,2,0,0,0,13

In [45]:
df2

,Erstsprache nach Schulstufe,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Stand: 02.10.2019 / Bildungsstatistik Kanton zh],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Jahr,Schulgemeinde,Erstsprache,KG,PS,PS Sonder,Sek A,Sek B,Sek C,Sek Sonder,Total
4,2016,Adlikon (Primar),Deutsch,0,12,0,NaN,NaN,NaN,NaN,12
...,...,...,...,...,...,...,...,...,...,...,...
4531,2016,Zürich-Zürichberg (Kreisschulpflege),Übrige osteuropäische Sprachen,0,3,0,0,0,0,0,3
4532,2016,Zürich-Zürichberg (Kreisschulpflege),Übrige slawische Sprachen,0,2,0,0,0,0,0,2
4533,2016,Zürich-Zürichberg (Kreisschulpflege),Übrige Sprachen,1,12,0,1,3,0,2,19
4534,2016,Zürich-Zürichberg (Kreisschulpflege),Übrige westasiatische Sprachen,0,0,0,0,1,0,0,1
4535,2016,Zürich-Zürichberg (Kreisschulpflege),Ungarisch,3,8,0,2,0,0,0,13

In [46]:
df1.dtypes

Erstsprache nach Schulstufe    object
Unnamed: 1                     object
Unnamed: 2                     object
Unnamed: 3                     object
Unnamed: 4                     object
Unnamed: 5                     object
Unnamed: 6                     object
Unnamed: 7                     object
Unnamed: 8                     object
Unnamed: 9                     object
Unnamed: 10                    object
dtype: object

In [49]:
df2.dtypes

Erstsprache nach Schulstufe    object
Unnamed: 1                     object
Unnamed: 2                     object
Unnamed: 3                     object
Unnamed: 4                     object
Unnamed: 5                     object
Unnamed: 6                     object
Unnamed: 7                     object
Unnamed: 8                     object
Unnamed: 9                     object
Unnamed: 10                    object
dtype: object

In [47]:
df1.shape

(4601, 11)

In [50]:
df2.shape

(4536, 11)

In [48]:
df1.describe()

,Erstsprache nach Schulstufe,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
count,4599,4598,4598,3905,3905,3905,3033,3033,3033,3033,4598
unique,3,195,47,134,227,14,111,76,24,13,303
top,2017,Zürich-Waidberg (Kreisschulpflege),Deutsch,0,1,0,0,0,0,0,1
freq,4597,45,194,1438,912,3681,1369,1418,2479,2903,1080

In [51]:
df2.describe()

,Erstsprache nach Schulstufe,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
count,4534,4533,4533,3844,3844,3844,2973,2973,2973,2973,4533
unique,3,195,48,138,228,13,115,72,24,15,295
top,2016,Zürich-Waidberg (Kreisschulpflege),Deutsch,0,1,0,0,0,0,0,1
freq,4532,46,194,1404,882,3595,1360,1383,2428,2819,1063

In [52]:
df1['Unnamed: 1'].value_counts().sort_index()

Adlikon (Primar)                             3
Adliswil (Einheitsgemeinde)                 36
Aesch (Primar)                               8
Aeugst a.A. (Primar)                        12
Affoltern a.A. (Primar)                     29
                                            ..
Zürich-Limmattal (Kreisschulpflege)         40
Zürich-Schwamendingen (Kreisschulpflege)    36
Zürich-Uto (Kreisschulpflege)               43
Zürich-Waidberg (Kreisschulpflege)          45
Zürich-Zürichberg (Kreisschulpflege)        39
Name: Unnamed: 1, Length: 195, dtype: int64

In [53]:
df2['Unnamed: 1'].value_counts().sort_index()

Adlikon (Primar)                             2
Adliswil (Einheitsgemeinde)                 38
Aesch (Primar)                               7
Aeugst a.A. (Primar)                        11
Affoltern a.A. (Primar)                     27
                                            ..
Zürich-Limmattal (Kreisschulpflege)         39
Zürich-Schwamendingen (Kreisschulpflege)    37
Zürich-Uto (Kreisschulpflege)               43
Zürich-Waidberg (Kreisschulpflege)          46
Zürich-Zürichberg (Kreisschulpflege)        38
Name: Unnamed: 1, Length: 195, dtype: int64

In [56]:
df_new = df1.merge(df2, how='inner', on='Unnamed: 1')
df_new.head(20)

,Erstsprache nach Schulstufe_x,Unnamed: 1,Unnamed: 2_x,Unnamed: 3_x,Unnamed: 4_x,Unnamed: 5_x,Unnamed: 6_x,Unnamed: 7_x,Unnamed: 8_x,Unnamed: 9_x,...,Erstsprache nach Schulstufe_y,Unnamed: 2_y,Unnamed: 3_y,Unnamed: 4_y,Unnamed: 5_y,Unnamed: 6_y,Unnamed: 7_y,Unnamed: 8_y,Unnamed: 9_y,Unnamed: 10_y
0,Stand: 02.10.2019 / Bildungsstatistik Kanton zh],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Stand: 02.10.2019 / Bildungsstatistik Kanton zh],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Stand: 02.10.2019 / Bildungsstatistik Kanton zh],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Stand: 02.10.2019 / Bildungsstatistik Kanton zh],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Stand: 02.10.2019 / Bildungsstatistik Kanton zh],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Stand: 02.10.2019 / Bildungsstatistik Kanton zh],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Jahr,Schulgemeinde,Erstsprache,KG,PS,PS Sonder,Sek A,Sek B,Sek C,Sek Sonder,...,Jahr,Erstsprache,KG,PS,PS Sonder,Sek A,Sek B,Sek C,Sek Sonder,Total
10,2017,Adlikon (Primar),Deutsch,0,12,0,NaN,NaN,NaN,NaN,...,2016,Deutsch,0,12,0,NaN,NaN,NaN,NaN,12
11,2017,Adlikon (Primar),Deutsch,0,12,0,NaN,NaN,NaN,NaN,...,2016,Übrige ostasiatische Sprachen,0,1,0,NaN,NaN,NaN,NaN,1
12,2017,Adlikon (Primar),Kurdisch,0,2,0,NaN,NaN,NaN,NaN,...,2016,Deutsch,0,12,0,NaN,NaN,NaN,NaN,12
13,2017,Adlikon (Primar),Kurdisch,0,2,0,NaN,NaN,NaN,NaN,...,2016,Übrige ostasiatische Sprachen,0,1,0,NaN,NaN,NaN,NaN,1
14,2017,Adlikon (Primar),Übrige ostasiatische Sprachen,0,1,0,NaN,NaN,NaN,NaN,...,2016,Deutsch,0,12,0,NaN,NaN,NaN,NaN,12
15,2017,Adlikon (Primar),Übrige ostasiatische Sprachen,0,1,0,NaN,NaN,NaN,NaN,...,2016,Übrige ostasiatische Sprachen,0,1,0,NaN,NaN,NaN,NaN,1
16,2017,Adliswil (Einheitsgemeinde),Albanisch,27,78,1,13,15,4,0,...,2016,Albanisch,23,82,0,13,13,6,0,137
17,2017,Adliswil (Einheitsgemeinde),Albanisch,27,78,1,13,15,4,0,...,2016,Arabisch,6,4,1,0,0,0,0,11
18,2017,Adliswil (Einheitsgemeinde),Albanisch,27,78,1,13,15,4,0,...,2016,Bosnisch,2,8,0,2,3,0,0,15
19,2017,Adliswil (Einheitsgemeinde),Albanisch,27,78,1,13,15,4,0,...,2016,Bulgarisch,0,2,0,1,0,0,0,3

In [11]:
df = pd.read_excel(path, na_values= {'KG',"PS","PS Sonder","Sek A","Sek B","Sek C","Sek Sonder","Total"})

In [12]:
df.dtypes

Erstsprache nach Schulstufe     object
Unnamed: 1                      object
Unnamed: 2                      object
Unnamed: 3                     float64
Unnamed: 4                     float64
Unnamed: 5                     float64
Unnamed: 6                     float64
Unnamed: 7                     float64
Unnamed: 8                     float64
Unnamed: 9                     float64
Unnamed: 10                    float64
dtype: object

In [13]:
df['Unnamed: 1'].unique()

array([nan, 'Schulgemeinde', 'Adlikon (Primar)',
       'Adliswil (Einheitsgemeinde)', 'Aesch (Primar)',
       'Aeugst a.A. (Primar)', 'Affoltern a.A. (Primar)',
       'Affoltern a.A.-Aeugst (Sekundar)', 'Altikon (Primar + Pol. Gem.)',
       'Andelfingen (Primar)', 'Andelfingen (Sekundar)',
       'Bachenbülach (Primar)', 'Bachs (Primar)',
       'Bäretswil (Einheitsgemeinde)', 'Bassersdorf (Einheitsgemeinde)',
       'Bauma-Sternenberg (Einheitsgemeinde)', 'Benken (Primar)',
       'Birmensdorf (Primar)', 'Birmensdorf-Aesch (Sekundar)',
       'Bonstetten (Primar + Pol. Gem.)', 'Bonstetten (Sekundar)',
       'Boppelsen (Primar)', 'Brütten (Einheitsgemeinde)',
       'Bubikon (Primar + Sekundar)', 'Buchs (Primar + Pol. Gem.)',
       'Bülach (Primar + Pol. Gem.)', 'Bülach (Sekundar)',
       'Dachsen (Primar)', 'Dägerlen (Primar)',
       'Dällikon (Primar + Pol. Gem.)', 'Dänikon-Hüttikon (Primar)',
       'Dättlikon (Einheitsgemeinde)', 'Dielsdorf (Primar)',
       'Dielsdorf (Sekundar)', 'Dietikon (Einheitsgemeinde)',
       'Dietlikon (Primar + Sekundar)', 'Dinhard (Primar + Pol. Gem.)',
       'Dübendorf (Primar + Pol. Gem.)',
       'Dübendorf-Schwerzenbach (Sekundar)', 'Dürnten (Einheitsgemeinde)',
       'Egg (Einheitsgemeinde)', 'Eglisau (Primar + Sekundar)',
       'Elgg (Primar)', 'Elgg (Sekundar)', 'Ellikon a.d.Th. (Primar)',
       'Elsau (Primar)', 'Elsau-Schlatt (Sekundar)',
       'Embrach (Primar + Pol. Gem.)', 'Embrach (Sekundar)',
       'Erlenbach (Einheitsgemeinde)',
       'Erlenbach-Herrliberg (Sek.schul Verband)',
       'Fällanden (Primar + Sekundar)', 'Fehraltorf (Einheitsgemeinde)',
       'Feuerthalen (Einheitsgemeinde)', 'Fischenthal (Einheitsgemeinde)',
       'Flaachtal (Primar + Sekundar)', 'Flurlingen (Primar)',
       'Glattfelden (Einheitsgemeinde)', 'Gossau (Primar + Sekundar)',
       'Greifensee (Primar + Pol. Gem.)', 'Grüningen (Primar + Sekundar)',
       'Hagenbuch (Primar + Pol. Gem.)',
       'Hausen a.A. (Primar + Pol. Gem.)', 'Hausen a.A. (Sekundar)',
       'Hedingen (Einheitsgemeinde)', 'Henggart (Primar + Pol. Gem.)',
       'Herrliberg (Einheitsgemeinde)', 'Hettlingen (Primar + Pol. Gem.)',
       'Hinwil (Primar + Sekundar)', 'Hirzel (Einheitsgemeinde)',
       'Hittnau (Primar + Sekundar)', 'Hochfelden (Primar)',
       'Hofstetten (Primar)', 'Hombrechtikon (Einheitsgemeinde)',
       'Horgen (Einheitsgemeinde)', 'Höri (Primar)', 'Humlikon (Primar)',
       'Hütten (Primar + Pol. Gem.)',
       'Illnau-Effretikon (Einheitsgemeinde)',
       'Kappel a.A. (Primar + Pol. Gem.)', 'Kilchberg (Einheitsgemeinde)',
       'Kilchberg-Rüschlikon (Sek.schul Verband)',
       'Kloten (Einheitsgemeinde)', 'Knonau (Primar + Pol. Gem.)',
       'Küsnacht (Primar + Sekundar)', 'Langnau a.A. (Einheitsgemeinde)',
       'Laufen-Uhwiesen (Primar)', 'Lindau (Einheitsgemeinde)',
       'Lufingen (Primar + Pol. Gem.)', 'Männedorf (Einheitsgemeinde)',
       'Marthalen (Primar)', 'Marthalen (Sekundar)',
       'Maschwanden (Primar)', 'Maur (Einheitsgemeinde)',
       'Meilen (Einheitsgemeinde)', 'Mettmenstetten (Primar)',
       'Mettmenstetten (Sekundar)', 'Mönchaltorf (Einheitsgemeinde)',
       'Nänikon-Greifensee (Sekundar)', 'Neerach (Primar)',
       'Neftenbach (Einheitsgemeinde)', 'Niederglatt (Primar)',
       'Niederhasli (Primar + Pol. Gem.)',
       'Niederhasli-Niederglatt (Sekundar)',
       'Nürensdorf (Einheitsgemeinde)', 'Oberembrach (Primar)',
       'Oberengstringen (Einheitsgemeinde)',
       'Oberglatt (Primar + Pol. Gem.)', 'Oberrieden (Einheitsgemeinde)',
       'Obfelden (Primar)', 'Obfelden-Ottenbach (Sekundar)',
       'Oetwil a.S. (Einheitsgemeinde)', 'Oetwil-Geroldswil (Primar)',
       'Opfikon (Einheitsgemeinde)', 'Ossingen (Primar)',
       'Ossingen (Sekundar)', 'Otelfingen (Primar + Pol. Gem.)',
       'Ottenbach (Primar)', 'Pfäffikon (Einheitsgemeinde)',
       'Pfungen (Einheitsgemeinde)', 'Rafz (Einheitsgemeinde)',
       'Regensberg (Primar)', 'Regensdorf (Primar)',
       'Regensdorf-Buchs-Dällikon (Sekundar)',
       'Rheinau (Primar + Pol. Gem.)', 'Richterswil (Einheitsgemeinde)',
       'Rickenbach (Primar + Pol. Gem.)', 'Rickenbach (Sekundar)',
       'Rifferswil (Primar + Pol. Gem.)',
       'Rorbas-Freienstein-Teufen (Primar + Sekundar)',
       'Rümlang (Primar)', 'Rümlang-Oberglatt (Sekundar)',
       'Rüschlikon (Einheitsgemeinde)', 'Russikon (Einheitsgemeinde)',
       'Rüti (Primar + Sekundar)', 'Schlatt (Primar)',
       'Schlieren (Einheitsgemeinde)', 'Schönenberg (Primar + Pol. Gem.)',
       'Schwerzenbach (Primar)', 'Seegräben (Primar + Pol. Gem.)',
       'Seuzach (Primar + Pol. Gem.)', 'Seuzach (Sekundar)',
       'Stadel (Primar)', 'Stadel (Sekundar)', 'Stäfa (Einheitsgemeinde)',
       'Stallikon (Primar + Pol. Gem.)', 'Stammertal (Primar + Sekundar)',
       'Steinmaur (Primar)', 'Thalheim a.d.Th. (Primar + Pol. Gem.)',
       'Thalwil (Einheitsgemeinde)', 'Trüllikon (Primar)',
       'Truttikon (Primar)', 'Turbenthal (Primar)',
       'Turbenthal-Wildberg (Sekundar)',
       'Uetikon a.S. (Einheitsgemeinde)', 'Uhwiesen (Sekundar)',
       'Uitikon (Primar + Sekundar)', 'Unterengstringen (Primar)',
       'Unteres Furttal (Sekundar)',
       'Unteres Rafzerfeld (Primar + Sekundar)',
       'Urdorf (Primar + Sekundar)', 'Uster (Primar + Pol. Gem.)',
       'Uster (Sekundar)', 'Volketswil (Primar + Sekundar)',
       'Wädenswil (Primar + Pol. Gem.)', 'Wädenswil (Sekundar)',
       'Wald (Einheitsgemeinde)', 'Wallisellen (Primar + Sekundar)',
       'Wangen-Brüttisellen (Einheitsgemeinde)',
       'Wehntal (Primar + Sekundar)', 'Weiach (Primar)',
       'Weiningen (Primar + Pol. Gem.)', 'Weiningen (Sekundar)',
       'Weisslingen (Einheitsgemeinde)', 'Wettswil a.A. (Primar)',
       'Wetzikon (Primar + Pol. Gem.)', 'Wetzikon-Seegräben (Sekundar)',
       'Wiesendangen-Bertschikon (Primar + Sekundar)', 'Wila (Primar)',
       'Wila (Sekundar)', 'Wildberg (Primar)', 'Winkel (Primar)',
       'Winterthur Seen-Mattenbach (Kreisschulpflege)',
       'Winterthur Stadt-Töss (Kreisschulpflege)',
       'Winterthur Veltheim-Wülflingen (Kreisschulpflege)',
       'Winterthur-Oberwinterthur (Kreisschulpflege)',
       'Zell (Einheitsgemeinde)', 'Zollikon (Einheitsgemeinde)',
       'Zumikon (Einheitsgemeinde)', 'Zürich-Glattal (Kreisschulpflege)',
       'Zürich-Letzi (Kreisschulpflege)',
       'Zürich-Limmattal (Kreisschulpflege)',
       'Zürich-Schwamendingen (Kreisschulpflege)',
       'Zürich-Uto (Kreisschulpflege)',
       'Zürich-Waidberg (Kreisschulpflege)',
       'Zürich-Zürichberg (Kreisschulpflege)'], dtype=object)

In [14]:
df.sort_values('Unnamed: 3', ascending=False).head(20)

,Erstsprache nach Schulstufe,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
4523,2017,Zürich-Waidberg (Kreisschulpflege),Deutsch,849.0,2425.0,0.0,376.0,59.0,0.0,0.0,3709.0
4480,2017,Zürich-Uto (Kreisschulpflege),Deutsch,745.0,2053.0,4.0,334.0,55.0,0.0,3.0,3194.0
4322,2017,Zürich-Glattal (Kreisschulpflege),Deutsch,622.0,1815.0,0.0,279.0,93.0,0.0,1.0,2810.0
4566,2017,Zürich-Zürichberg (Kreisschulpflege),Deutsch,601.0,1923.0,2.0,386.0,27.0,0.0,0.0,2939.0
3513,2017,Uster (Primar + Pol. Gem.),Deutsch,553.0,1390.0,0.0,NaN,NaN,NaN,NaN,1943.0
4363,2017,Zürich-Letzi (Kreisschulpflege),Deutsch,530.0,1247.0,0.0,163.0,65.0,0.0,0.0,2005.0
4404,2017,Zürich-Limmattal (Kreisschulpflege),Deutsch,381.0,830.0,0.0,89.0,27.0,0.0,0.0,1327.0
4071,2017,Winterthur Seen-Mattenbach (Kreisschulpflege),Deutsch,345.0,911.0,3.0,232.0,67.0,8.0,0.0,1566.0
4190,2017,Winterthur-Oberwinterthur (Kreisschulpflege),Deutsch,298.0,711.0,0.0,175.0,50.0,0.0,4.0,1238.0
4113,2017,Winterthur Stadt-Töss (Kreisschulpflege),Deutsch,293.0,722.0,0.0,150.0,40.0,7.0,0.0,1212.0
4153,2017,Winterthur Veltheim-Wülflingen (Kreisschulpflege),Deutsch,290.0,737.0,1.0,178.0,65.0,9.0,0.0,1280.0
3622,2017,Wädenswil (Primar + Pol. Gem.),Deutsch,256.0,663.0,8.0,NaN,NaN,NaN,NaN,927.0
3936,2017,Wetzikon (Primar + Pol. Gem.),Deutsch,255.0,728.0,0.0,NaN,NaN,NaN,NaN,983.0
4444,2017,Zürich-Schwamendingen (Kreisschulpflege),Deutsch,239.0,728.0,0.0,119.0,49.0,0.0,0.0,1135.0
2012,2017,Meilen (Einheitsgemeinde),Deutsch,237.0,570.0,0.0,102.0,21.0,0.0,0.0,930.0
3264,2017,Thalwil (Einheitsgemeinde),Deutsch,223.0,578.0,0.0,104.0,36.0,6.0,0.0,947.0
2581,2017,Pfäffikon (Einheitsgemeinde),Deutsch,222.0,536.0,0.0,103.0,65.0,11.0,0.0,937.0
2751,2017,Richterswil (Einheitsgemeinde),Deutsch,222.0,562.0,0.0,169.0,56.0,3.0,0.0,1012.0
3584,2017,Volketswil (Primar + Sekundar),Deutsch,208.0,658.0,0.0,178.0,82.0,15.0,0.0,1141.0
1629,2017,Illnau-Effretikon (Einheitsgemeinde),Deutsch,207.0,534.0,5.0,139.0,66.0,11.0,0.0,962.0

In [29]:
df[df['Unnamed: 1'] == {'Adliswil (Einheitsgemeinde)',
   "Wädenswil (Primar + Pol. Gem.)"}].sort_values('Unnamed: 3', ascending=False).head()

Empty DataFrame
Columns: [Erstsprache nach Schulstufe, Unnamed: 1, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10]
Index: []

In [16]:
seegemeinden = df['Unnamed: 1'] == {"Adliswil (Einheitsgemeinde)","Wädenswil (Primar + Pol. Gem.)"}

In [22]:
df[seegemeinden]

Empty DataFrame
Columns: [Erstsprache nach Schulstufe, Unnamed: 1, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10]
Index: []

In [23]:
df[seegemeinden].sort_values('Unnamed: 3', ascending=False).head(10)

Empty DataFrame
Columns: [Erstsprache nach Schulstufe, Unnamed: 1, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10]
Index: []

In [56]:
df.rename(columns={"Unnamed: 1": "Schulgemeinde","Unnamed: 2": "Sprache",
                   'Unnamed: 3': 'Kindergarten','Unnamed: 4': 'Primarschule',
                   "Unnamed: 5":"Primar Sonder","Unnamed: 6":"Sek A"})

,Erstsprache nach Schulstufe,Schulgemeinde,Sprache,Kindergarten,Primarschule,Primar Sonder,Sek A,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Stand: 02.10.2019 / Bildungsstatistik Kanton zh],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Jahr,Schulgemeinde,Erstsprache,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017,Adlikon (Primar),Deutsch,0.0,12.0,0.0,NaN,NaN,NaN,NaN,12.0
...,...,...,...,...,...,...,...,...,...,...,...
4596,2017,Zürich-Zürichberg (Kreisschulpflege),Übrige osteuropäische Sprachen,0.0,3.0,0.0,0.0,0.0,0.0,0.0,3.0
4597,2017,Zürich-Zürichberg (Kreisschulpflege),Übrige slawische Sprachen,0.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0
4598,2017,Zürich-Zürichberg (Kreisschulpflege),Übrige Sprachen,0.0,11.0,0.0,0.0,0.0,0.0,1.0,12.0
4599,2017,Zürich-Zürichberg (Kreisschulpflege),Übrige westasiatische Sprachen,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4600,2017,Zürich-Zürichberg (Kreisschulpflege),Ungarisch,2.0,9.0,0.0,2.0,0.0,0.0,0.0,13.0