In [2]:
import pandas as pd
import numpy as np
%matplotlib inline

In [3]:
path = "Erstsprache/Erstsprache nach Schulstufe_2017.xls"

In [4]:
df = pd.read_excel(path)

In [5]:
df

,Erstsprache nach Schulstufe,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Stand: 02.10.2019 / Bildungsstatistik Kanton zh],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Jahr,Schulgemeinde,Erstsprache,KG,PS,PS Sonder,Sek A,Sek B,Sek C,Sek Sonder,Total
4,2017,Adlikon (Primar),Deutsch,0,12,0,NaN,NaN,NaN,NaN,12
...,...,...,...,...,...,...,...,...,...,...,...
4596,2017,Zürich-Zürichberg (Kreisschulpflege),Übrige osteuropäische Sprachen,0,3,0,0,0,0,0,3
4597,2017,Zürich-Zürichberg (Kreisschulpflege),Übrige slawische Sprachen,0,2,0,0,0,0,0,2
4598,2017,Zürich-Zürichberg (Kreisschulpflege),Übrige Sprachen,0,11,0,0,0,0,1,12
4599,2017,Zürich-Zürichberg (Kreisschulpflege),Übrige westasiatische Sprachen,0,1,0,0,0,0,0,1
4600,2017,Zürich-Zürichberg (Kreisschulpflege),Ungarisch,2,9,0,2,0,0,0,13

In [6]:
df.dtypes

Erstsprache nach Schulstufe    object
Unnamed: 1                     object
Unnamed: 2                     object
Unnamed: 3                     object
Unnamed: 4                     object
Unnamed: 5                     object
Unnamed: 6                     object
Unnamed: 7                     object
Unnamed: 8                     object
Unnamed: 9                     object
Unnamed: 10                    object
dtype: object

In [7]:
df.shape

(4601, 11)

In [8]:
df.describe()

,Erstsprache nach Schulstufe,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
count,4599,4598,4598,3905,3905,3905,3033,3033,3033,3033,4598
unique,3,195,47,134,227,14,111,76,24,13,303
top,2017,Zürich-Waidberg (Kreisschulpflege),Deutsch,0,1,0,0,0,0,0,1
freq,4597,45,194,1438,912,3681,1369,1418,2479,2903,1080

In [9]:
df['Unnamed: 1'].value_counts().sort_index()

Adlikon (Primar)                             3
Adliswil (Einheitsgemeinde)                 36
Aesch (Primar)                               8
Aeugst a.A. (Primar)                        12
Affoltern a.A. (Primar)                     29
                                            ..
Zürich-Limmattal (Kreisschulpflege)         40
Zürich-Schwamendingen (Kreisschulpflege)    36
Zürich-Uto (Kreisschulpflege)               43
Zürich-Waidberg (Kreisschulpflege)          45
Zürich-Zürichberg (Kreisschulpflege)        39
Name: Unnamed: 1, Length: 195, dtype: int64

In [15]:
df = pd.read_excel(path, na_values= {'KG',"PS","PS Sonder","Sek A","Sek B","Sek C","Sek Sonder","Total"})

In [16]:
df.dtypes

Erstsprache nach Schulstufe     object
Unnamed: 1                      object
Unnamed: 2                      object
Unnamed: 3                     float64
Unnamed: 4                     float64
Unnamed: 5                     float64
Unnamed: 6                     float64
Unnamed: 7                     float64
Unnamed: 8                     float64
Unnamed: 9                     float64
Unnamed: 10                    float64
dtype: object

In [19]:
df.sort_values('Unnamed: 3', ascending=False).tail(10)

,Erstsprache nach Schulstufe,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
3991,2017,Wetzikon-Seegräben (Sekundar),Übrige Sprachen,NaN,NaN,NaN,1.0,1.0,1.0,0.0,3.0
3992,2017,Wetzikon-Seegräben (Sekundar),Übrige westasiatische Sprachen,NaN,NaN,NaN,0.0,1.0,0.0,0.0,1.0
3993,2017,Wetzikon-Seegräben (Sekundar),Ungarisch,NaN,NaN,NaN,4.0,0.0,0.0,0.0,4.0
4027,2017,Wila (Sekundar),Albanisch,NaN,NaN,NaN,1.0,2.0,1.0,0.0,4.0
4028,2017,Wila (Sekundar),Deutsch,NaN,NaN,NaN,42.0,21.0,2.0,0.0,65.0
4029,2017,Wila (Sekundar),Französisch,NaN,NaN,NaN,1.0,0.0,0.0,0.0,1.0
4030,2017,Wila (Sekundar),Italienisch,NaN,NaN,NaN,0.0,1.0,1.0,0.0,2.0
4031,2017,Wila (Sekundar),Polnisch,NaN,NaN,NaN,1.0,0.0,0.0,0.0,1.0
4032,2017,Wila (Sekundar),Portugiesisch,NaN,NaN,NaN,0.0,0.0,1.0,0.0,1.0
4033,2017,Wila (Sekundar),Tamil,NaN,NaN,NaN,1.0,0.0,0.0,0.0,1.0

In [23]:
df[df['Unnamed: 1'] == 'Adliswil (Einheitsgemeinde)'].sort_values('Unnamed: 3', ascending=False).head(10)

,Erstsprache nach Schulstufe,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
13,2017,Adliswil (Einheitsgemeinde),Deutsch,170.0,459.0,0.0,90.0,26.0,2.0,0.0,747.0
14,2017,Adliswil (Einheitsgemeinde),Englisch,36.0,70.0,0.0,10.0,2.0,1.0,0.0,119.0
7,2017,Adliswil (Einheitsgemeinde),Albanisch,27.0,78.0,1.0,13.0,15.0,4.0,0.0,138.0
19,2017,Adliswil (Einheitsgemeinde),Italienisch,23.0,71.0,0.0,14.0,14.0,3.0,0.0,125.0
28,2017,Adliswil (Einheitsgemeinde),Russisch,18.0,20.0,1.0,3.0,1.0,0.0,0.0,43.0
40,2017,Adliswil (Einheitsgemeinde),Übrige Sprachen,16.0,28.0,2.0,5.0,0.0,0.0,0.0,51.0
24,2017,Adliswil (Einheitsgemeinde),Polnisch,14.0,12.0,0.0,1.0,1.0,0.0,0.0,28.0
25,2017,Adliswil (Einheitsgemeinde),Portugiesisch,14.0,45.0,0.0,8.0,13.0,2.0,0.0,82.0
33,2017,Adliswil (Einheitsgemeinde),Spanische Sprachen,11.0,30.0,1.0,11.0,5.0,0.0,0.0,58.0
42,2017,Adliswil (Einheitsgemeinde),Ungarisch,10.0,30.0,0.0,4.0,0.0,0.0,0.0,44.0